pipeline {
    agent none



    
    
    stages {

        stage('git-clone') {
        agent any
        steps{
            checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/edk2010/final-project.git']])


        }
        }
        stage('build-docker') {
            agent any
            steps {
                sh 'cd final-project/employees'
                sh 'docker build . project-tl:1'
            }
        }
        stage('upload-docker'){
            agent any

            steps{

                sh 'echo "hello word"'
       

            }



        }
        stage('test-app'){
            agent {
                docker{image 'project-tl:1'}
            }

            steps{
                sh 'cd /app/final-project/employees'
                sh 'python -m unitest.py'


            }
        }

        
    }

}
